### ISSUE TITLE
🐛bug: Operation is not supported on this platform.

### ISSUE THREAD

**Issue by neozhu** [iluvadev/PocketBaseClient#46]
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at pocketbase_csharp_sdk.PocketBase.Send[PagedCollectionModel`1](String path, HttpMethod method, IDictionary`2 headers, IDictionary`2 query, IDictionary`2 body, IEnumerable`1 files, CancellationToken cancellationToken) in D:\github\BlazorPocketApp\sdk\pocketbase-csharp-sdk\PocketBase.cs:line 249

https://github.com/dotnet/maui/issues/10470

![image](https://github.com/iluvadev/PocketBaseClient/assets/1549611/87d4cacd-b362-45d5-a690-a94f51e46744)

  not support synchronized methods in web assembly

**Comment by neozhu** [comment]
https://github.com/dotnet/runtime/blob/1281a4a3393e9293aa4b379d619a692d6dcb62a4/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.AnyMobile.cs#L710

**Comment by neozhu** [comment]
I have fixed this bug and 
imp IAsyncEnumerable<T>,  GetItemsInternalAsync,GetPagedItemsAsync, GetPagedItems
![image](https://github.com/iluvadev/PocketBaseClient/assets/1549611/f9b525d2-0aaf-45b3-96cc-a49040f53b9c)

**Comment by VictorioBerra** [comment]
@iluvadev is this library still supported? I am considering using it but there is multiple issues that are going unanswered.

**Comment by neozhu** [comment]
> @iluvadev is this library still supported? I am considering using it but there is multiple issues that are going unanswered.


If possible, I would also like to join the collaborative project. I have fixed and enhanced some functions.

**Comment by iluvadev** [comment]
> > @iluvadev is this library still supported? I am considering using it but there is multiple issues that are going unanswered.
> 
> If possible, I would also like to join the collaborative project. I have fixed and enhanced some functions.

Hello, I haven't had time to spend on my open projects for a long time...
@neozhu thank you very much for the trust and for wanting to continue the development that I can't push forward now. I have added you as a contributor.

I'm so sorry I didn't respond to all open topics.
